<a href="https://colab.research.google.com/github/jlivu/intro_to_deep_learning_with_pytorch/blob/main/2_intro_to_deep_learning_with_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# TENSORS

In [3]:
import torch
import numpy as np

In [5]:
# LISTS

In [7]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [8]:
# NUMPY ARRAYS

In [9]:
np1 = np.random.rand(3,4)
np1

array([[0.69453976, 0.71207206, 0.27538046, 0.02590359],
       [0.85268966, 0.80078312, 0.51101776, 0.67008645],
       [0.52884472, 0.00691297, 0.96863278, 0.7521778 ]])

In [11]:
np1.dtype

dtype('float64')

In [13]:
np2 = np.random.rand(3)
np2

array([0.66484279, 0.66472745, 0.00832169])

In [14]:
# TENSORS

In [18]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.5496,  0.2157,  2.4293, -1.0323],
        [-0.2630,  0.0143, -2.0625,  0.0757],
        [ 0.3985,  0.2713,  0.0874,  1.1939]])

In [24]:
tensor_2d.dtype

torch.float32

In [20]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
## Create tensor out of a numpy array

In [22]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6945, 0.7121, 0.2754, 0.0259],
        [0.8527, 0.8008, 0.5110, 0.6701],
        [0.5288, 0.0069, 0.9686, 0.7522]], dtype=torch.float64)