<a href="https://colab.research.google.com/github/jlivu/intro_to_deep_learning_with_pytorch/blob/main/3_intro_to_deep_learning_with_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Tensor Operations

In [2]:
import torch

In [5]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
# RESHAPE AND VIEW

In [30]:
# Reshape operations

In [10]:
# Doesn't meet the number of items to be shaped (would need 12 items)
my_torch2 = my_torch.reshape(2,6)
my_torch2

RuntimeError: shape '[2, 6]' is invalid for input of size 10

In [11]:
# Reshape if we don't know the number of items using -1

In [12]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch3 = my_torch3.reshape(2,-1)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
# Again, doesn't meet the number of items,
# number of items don't match up
my_torch4 = torch.arange(15)
my_torch4

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
my_torch4_reshape1 = my_torch4.reshape(2,-1)
my_torch4_reshape1

RuntimeError: shape '[2, -1]' is invalid for input of size 15

In [27]:
my_torch4_reshape2 = my_torch4.reshape(3,-1)
my_torch4_reshape2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [28]:
# Opposite direction
my_torch4_reshape3 = my_torch4.reshape(-1,5)
my_torch4_reshape3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [31]:
# View operations

In [33]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
my_torch5_view1 = my_torch5.view(2,5)
my_torch5_view1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [35]:
# with reshape and view, they will update

In [49]:
my_torch6 = torch.arange(10)
my_torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# change one of the items in the array

In [50]:
# reshape
my_torch6_reshape1 = my_torch6.reshape(-1,5)
my_torch6_reshape1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [52]:
# change the second item (replace the value 1 with 4141)
my_torch6[1] = 4141
my_torch6

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [55]:
# my_torch6_reshape1 will change as well
# changes/updates to my_torch6 are replicated in other tensors that use my_torch6
my_torch6_reshape1

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [54]:
# SLICES

In [56]:
# Slices allow you to get a section of a tensor

In [58]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# Grab a specific item
my_torch7_item = my_torch7[7]
my_torch7_item

tensor(7)

In [64]:
# Grab a slice
my_torch7_shape1 = my_torch7.reshape(5,2)
my_torch7_shape1

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [67]:
# Grab the 2nd column of the my_torch7_shape1 array
my_torch7_slice1 = my_torch7_shape1 [:,1]
my_torch7_slice1

tensor([1, 3, 5, 7, 9])

In [68]:
# Looks like a list.
# What if we want to keep the shape as in my_torch7_shape1?

In [69]:
# In that case, we want to return a column
my_torch7_slice2 = my_torch7_shape1 [:,1:]
my_torch7_slice2

tensor([[1],
        [3],
        [5],
        [7],
        [9]])